[package]
name = "GhoulOS"
version = "0.1.0"
edition = "2021"
authors= ["Hamza Hamud"]

[dependencies]
bootloader = "0.9.8"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
